### ISSUE TITLE
Issue with "fields" command

### ISSUE THREAD

**Issue by bertinatto** [scrapinghub/shubc#5]
The following command return all items' fields, not just the "url":

`shubc items XXXX -fields="url"`

**Comment by andrix** [comment]
@bertinatto I couldn't reproduce this issue, but you're using the options in the wrong other, it should be:

```
shubc -fields url items <job_id>
```

Can you check?

**Comment by bertinatto** [comment]
@andrix 
Yes, the problem was the options' order.
Thanks.

**Comment by andrix** [comment]
Thanks! Closing it.
