### ISSUE TITLE
Comma separated fields

### ISSUE THREAD

**Issue by bertinatto** [scrapinghub/shubc#9]
From the "help" command:

```
  -fields="": When -csv given, list of comma separated fields to include in the CSV
```

That said, when I run the following command, I get the item list as expected:

```
shubc -csv -fields field1,field2 items job_id
```

However, if I put an extra space between the field names, I get an error:

```
shubc -csv -fields field1, field2 items job_id

shubc: 'url' command not found
```

Maybe it's going to be more apropriate if (1) we allow that extra space after the comma; or (2) we report a message telling the user to fix the command.

**Comment by andrix** [comment]
@bertinatto - It's not an issue is the way the shell give the arguments to the program, and args parsing libraries works.

Take as a quick example here:

```
% python -c"import sys; print sys.argv" --arg=f1, f2, f3
['-c', '--arg=f1,', 'f2,', 'f3']
```

however, 

```
% python -c"import sys; print sys.argv" --arg=f1,f2,f3 
['-c', '--arg=f1,f2,f3']
```

Which in the last one, the parsing library will parse that as `arg = [f1, f2, f3]`.

Closing as invalid.
